In [1]:
import numpy as np
#1d
arr=np.array([1,2])
#2d
arr1=np.array([[1,2],[3,4]])
#3d
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr.shape)
print(arr2.shape)
print(arr2.shape)

(2,)
(2, 2, 2)
(2, 2, 2)


array rep understanding
1. 1d
arr = [1, 2]
Shape: (2,)
Just one axis with two elements.

2. 2D
arr1 = [
    [1, 2],
    [3, 4]
]
Shape: (2, 2)
- Two rows, two columns.




3. 3D
arr2 = [
    [
        [1, 2],  # First row, first block
        [3, 4]   # Second row, first block
    ],
    [
        [5, 6],  # First row, second block
        [7, 8]   # Second row, second block
    ]
]
Shape: (2, 2, 2)
Visualizing the structure
Each block represents a separate 2D array:
Block 1 (Depth level 0):
1  2
3  4
Block 2 (Depth level 1):
5  6
7  8


Understanding Shape (2, 2, 2)
- First 2 → Number of blocks (Depth layers)
- Second 2 → Number of rows within each block
- Third 2 → Number of columns within each row

How to Index Elements?
You use arr2[depth, row, column]. Example:
- arr2[0, 0, 1] → First block (depth 0), first row (row 0), second column (column 1) → Value = 2
- arr2[1, 1, 0] → Second block (depth 1), second row (row 1), first column (column 0) → Value = 7





In [ ]:
#arange and reshape
arr10=np.arange(0,10,2).reshape(5,1)
print(arr10)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [7]:
#np.ones
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
#np.eye
b=np.eye(9)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bitwise

In [10]:


arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([10, 20, 30, 40, 50])

# Addition
add_result = arr2 + arr3

# Subtraction
sub_result = arr2 - arr3

# Multiplication
mul_result = arr2 * arr3

# Division
div_result = arr2 / arr3

print("Addition:", add_result)
print("Subtraction:", sub_result)
print("Multiplication:", mul_result)
print("Division:", div_result)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [12]:
#universal function
print(np.sqrt(arr2))
print(np.exp(arr2))
print(np.sin(arr2))
print(np.log(arr2))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [16]:
#slicling
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[2,0:3])
print(arr[0:2])

[ 9 10 11]
[[1 2 3 4]
 [5 6 7 8]]


In [19]:
import numpy as np

# Creating a NumPy array with dtype=object to store lists
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=object)

# Modifying a specific element
arr[0][4] = [13]  # Storing a list at index [0][4]

print(arr)

[[1 2 3 4 list([13])]
 [6 7 8 9 10]]


In [23]:
import numpy as np
from scipy.stats import mode  # Import mode function from SciPy

d = np.array([1, 2, 3, 4, 5])

# Mean
m = np.mean(d)

# Median
n = np.median(d)

# Mode
k = np.var(d)  # This returns a ModeResult object

print("Mean:", m)
print("Median:", n)
print("variance",k)  # Extract the mode value

Mean: 3.0
Median: 3.0
variance 2.0


In [ ]:
#logical
d>5

array([False, False, False, False, False])